version: 2.1

executors:
  nodejs:
    docker:
      - image: 'circleci/node:12.11.0'
    working_directory: ~/chrome-leetcode-submit-extension

jobs:
  build:
    executor: nodejs
    steps:
      - checkout
      - restore_cache:
          key: node_modules-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: download dependencies
          command: npm install
      - save_cache:
          key: node_modules-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: compile
          command: npm run build
      - run:
          name: Zip the extension
          command: zip chrome-leetcode-submit-extension.zip -r dist
      - persist_to_workspace:
          paths:
            - chrome-leetcode-submit-extension.zip
          root: ~/chrome-leetcode-submit-extension

# orbs:
  # cws: sugarshin/chrome-webstore@0.0.3

workflows:
  build_publish:
    jobs:
      - build
#       - cws/upload:
#           attach-workspace: true
#           auto-publish: true
#           checkout: false
#           executor: nodejs
#           extension-id: pdeaikmjefgminiagmbdhjlmoaoobbjc
#           source: chrome-leetcode-submit-extension.zip
#           workspace-root: ~/chrome-leetcode-submit-extension
#           requires:
#             - build
#           # Only run this job on git tag pushes
#           filters:
#             branches:
#               ignore: /.*/
#             tags:
#               only: /^v.*/
